#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : libXcursor
Version  : 1.1.14
Release  : 9
URL      : http://xorg.freedesktop.org/releases/individual/lib/libXcursor-1.1.14.tar.gz
Source0  : http://xorg.freedesktop.org/releases/individual/lib/libXcursor-1.1.14.tar.gz
Summary  : X Cursor Library
Group    : Development/Tools
License  : HPND
Requires: libXcursor-lib
Requires: libXcursor-doc
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkgconfig(32fixesproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xextproto)
BuildRequires : pkgconfig(32xfixes)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xrender)
BuildRequires : pkgconfig(fixesproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xextproto)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrender)

%description
libXcursor - X Window System Cursor management library
All questions regarding this software should be directed at the
Xorg mailing list:

%package dev
Summary: dev components for the libXcursor package.
Group: Development
Requires: libXcursor-lib
Provides: libXcursor-devel

%description dev
dev components for the libXcursor package.


%package dev32
Summary: dev32 components for the libXcursor package.
Group: Default
Requires: libXcursor-lib32
Requires: libXcursor-dev

%description dev32
dev32 components for the libXcursor package.


%package doc
Summary: doc components for the libXcursor package.
Group: Documentation

%description doc
doc components for the libXcursor package.


%package lib
Summary: lib components for the libXcursor package.
Group: Libraries

%description lib
lib components for the libXcursor package.


%package lib32
Summary: lib32 components for the libXcursor package.
Group: Default

%description lib32
lib32 components for the libXcursor package.


%prep
%setup -q -n libXcursor-1.1.14
pushd ..
cp -a libXcursor-1.1.14 build32
popd

%build
export LANG=C
export SOURCE_DATE_EPOCH=1484498150
%configure --disable-static
make V=1  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export CFLAGS="$CFLAGS -m32"
export CXXFLAGS="$CXXFLAGS -m32"
export LDFLAGS="$LDFLAGS -m32"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make V=1  %{?_smp_mflags}
popd
%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1484498150
rm -rf %{buildroot}
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
%make_install

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xcursor/Xcursor.h
/usr/lib64/libXcursor.so
/usr/lib64/pkgconfig/xcursor.pc

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXcursor.so
/usr/lib32/pkgconfig/32xcursor.pc
/usr/lib32/pkgconfig/xcursor.pc

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man3/*

%files lib
%defattr(-,root,root,-)
/usr/lib64/libXcursor.so.1
/usr/lib64/libXcursor.so.1.0.2

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXcursor.so.1
/usr/lib32/libXcursor.so.1.0.2
