#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXcursor
Version  : 1.2.1
Release  : 22
URL      : https://www.x.org/releases/individual/lib/libXcursor-1.2.1.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXcursor-1.2.1.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libXcursor-1.2.1.tar.gz.sig
Summary  : X Cursor Library
Group    : Development/Tools
License  : HPND
Requires: libXcursor-lib = %{version}-%{release}
Requires: libXcursor-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : pkg-config
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(fixesproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrender)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libXcursor - X Window System Cursor management library
------------------------------------------------------

%package dev
Summary: dev components for the libXcursor package.
Group: Development
Requires: libXcursor-lib = %{version}-%{release}
Provides: libXcursor-devel = %{version}-%{release}
Requires: libXcursor = %{version}-%{release}

%description dev
dev components for the libXcursor package.


%package lib
Summary: lib components for the libXcursor package.
Group: Libraries
Requires: libXcursor-license = %{version}-%{release}

%description lib
lib components for the libXcursor package.


%package license
Summary: license components for the libXcursor package.
Group: Default

%description license
license components for the libXcursor package.


%prep
%setup -q -n libXcursor-1.2.1
cd %{_builddir}/libXcursor-1.2.1
pushd ..
cp -a libXcursor-1.2.1 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1689722579
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FCFLAGS="$FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export FFLAGS="$FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
%configure --disable-static
make  %{?_smp_mflags}

unset PKG_CONFIG_PATH
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3"
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3"
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3"
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1689722579
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXcursor
cp %{_builddir}/libXcursor-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libXcursor/dc664605fdc1798afd260114aa223682b7d810cd || :
pushd ../buildavx2/
%make_install_v3
popd
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xcursor/Xcursor.h
/usr/lib64/libXcursor.so
/usr/lib64/pkgconfig/xcursor.pc
/usr/share/man/man3/Xcursor.3
/usr/share/man/man3/XcursorAnimateCreate.3
/usr/share/man/man3/XcursorAnimateDestroy.3
/usr/share/man/man3/XcursorAnimateNext.3
/usr/share/man/man3/XcursorCommentCreate.3
/usr/share/man/man3/XcursorCommentDestroy.3
/usr/share/man/man3/XcursorCommentsCreate.3
/usr/share/man/man3/XcursorCommentsDestroy.3
/usr/share/man/man3/XcursorCursorsCreate.3
/usr/share/man/man3/XcursorCursorsDestroy.3
/usr/share/man/man3/XcursorFileLoad.3
/usr/share/man/man3/XcursorFileLoadAllImages.3
/usr/share/man/man3/XcursorFileLoadImage.3
/usr/share/man/man3/XcursorFileLoadImages.3
/usr/share/man/man3/XcursorFileSave.3
/usr/share/man/man3/XcursorFileSaveImages.3
/usr/share/man/man3/XcursorFilenameLoad.3
/usr/share/man/man3/XcursorFilenameLoadAllImages.3
/usr/share/man/man3/XcursorFilenameLoadCursor.3
/usr/share/man/man3/XcursorFilenameLoadCursors.3
/usr/share/man/man3/XcursorFilenameLoadImage.3
/usr/share/man/man3/XcursorFilenameLoadImages.3
/usr/share/man/man3/XcursorFilenameSave.3
/usr/share/man/man3/XcursorFilenameSaveImages.3
/usr/share/man/man3/XcursorGetDefaultSize.3
/usr/share/man/man3/XcursorGetTheme.3
/usr/share/man/man3/XcursorGetThemeCore.3
/usr/share/man/man3/XcursorImageCreate.3
/usr/share/man/man3/XcursorImageDestroy.3
/usr/share/man/man3/XcursorImageHash.3
/usr/share/man/man3/XcursorImageLoadCursor.3
/usr/share/man/man3/XcursorImagesCreate.3
/usr/share/man/man3/XcursorImagesDestroy.3
/usr/share/man/man3/XcursorImagesLoadCursor.3
/usr/share/man/man3/XcursorImagesLoadCursors.3
/usr/share/man/man3/XcursorImagesSetName.3
/usr/share/man/man3/XcursorLibraryLoadCursor.3
/usr/share/man/man3/XcursorLibraryLoadCursors.3
/usr/share/man/man3/XcursorLibraryLoadImage.3
/usr/share/man/man3/XcursorLibraryLoadImages.3
/usr/share/man/man3/XcursorLibraryPath.3
/usr/share/man/man3/XcursorLibraryShape.3
/usr/share/man/man3/XcursorNoticeCreateBitmap.3
/usr/share/man/man3/XcursorNoticePutBitmap.3
/usr/share/man/man3/XcursorSetDefaultSize.3
/usr/share/man/man3/XcursorSetTheme.3
/usr/share/man/man3/XcursorSetThemeCore.3
/usr/share/man/man3/XcursorShapeLoadCursor.3
/usr/share/man/man3/XcursorShapeLoadCursors.3
/usr/share/man/man3/XcursorShapeLoadImage.3
/usr/share/man/man3/XcursorShapeLoadImages.3
/usr/share/man/man3/XcursorSupportsARGB.3
/usr/share/man/man3/XcursorSupportsAnim.3
/usr/share/man/man3/XcursorTryShapeBitmapCursor.3
/usr/share/man/man3/XcursorTryShapeCursor.3
/usr/share/man/man3/XcursorXcFileLoad.3
/usr/share/man/man3/XcursorXcFileLoadAllImages.3
/usr/share/man/man3/XcursorXcFileLoadImage.3
/usr/share/man/man3/XcursorXcFileLoadImages.3
/usr/share/man/man3/XcursorXcFileSave.3

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libXcursor.so.1.0.2
/usr/lib64/libXcursor.so.1
/usr/lib64/libXcursor.so.1.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXcursor/dc664605fdc1798afd260114aa223682b7d810cd
