#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
# Using build pattern: configure
# autospec version: v4
# autospec commit: e738c51
#
# Source0 file verified with key 0xCFDF148828C642A7 (alanc@freedesktop.org)
#
Name     : libXcursor
Version  : 1.2.2
Release  : 24
URL      : https://www.x.org/releases/individual/lib/libXcursor-1.2.2.tar.gz
Source0  : https://www.x.org/releases/individual/lib/libXcursor-1.2.2.tar.gz
Source1  : https://www.x.org/releases/individual/lib/libXcursor-1.2.2.tar.gz.sig
Summary  : X Cursor Library
Group    : Development/Tools
License  : HPND
Requires: libXcursor-lib = %{version}-%{release}
Requires: libXcursor-license = %{version}-%{release}
BuildRequires : buildreq-configure
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : pkg-config
BuildRequires : pkgconfig(32fixesproto)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xfixes)
BuildRequires : pkgconfig(32xorg-macros)
BuildRequires : pkgconfig(32xrender)
BuildRequires : pkgconfig(fixesproto)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xfixes)
BuildRequires : pkgconfig(xorg-macros)
BuildRequires : pkgconfig(xrender)
# Suppress stripping binaries
%define __strip /bin/true
%define debug_package %{nil}

%description
libXcursor - X Window System Cursor management library
------------------------------------------------------

%package dev
Summary: dev components for the libXcursor package.
Group: Development
Requires: libXcursor-lib = %{version}-%{release}
Provides: libXcursor-devel = %{version}-%{release}
Requires: libXcursor = %{version}-%{release}

%description dev
dev components for the libXcursor package.


%package dev32
Summary: dev32 components for the libXcursor package.
Group: Default
Requires: libXcursor-lib32 = %{version}-%{release}
Requires: libXcursor-dev = %{version}-%{release}

%description dev32
dev32 components for the libXcursor package.


%package lib
Summary: lib components for the libXcursor package.
Group: Libraries
Requires: libXcursor-license = %{version}-%{release}

%description lib
lib components for the libXcursor package.


%package lib32
Summary: lib32 components for the libXcursor package.
Group: Default
Requires: libXcursor-license = %{version}-%{release}

%description lib32
lib32 components for the libXcursor package.


%package license
Summary: license components for the libXcursor package.
Group: Default

%description license
license components for the libXcursor package.


%prep
%setup -q -n libXcursor-1.2.2
cd %{_builddir}/libXcursor-1.2.2
pushd ..
cp -a libXcursor-1.2.2 build32
popd
pushd ..
cp -a libXcursor-1.2.2 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1709573865
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export GOAMD64=v2
%configure --disable-static
make  %{?_smp_mflags}

pushd ../build32/
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig:/usr/share/pkgconfig"
ASFLAGS="${CLEAR_INTERMEDIATE_ASFLAGS}${CLEAR_INTERMEDIATE_ASFLAGS:+ }--32"
CFLAGS="${CLEAR_INTERMEDIATE_CFLAGS}${CLEAR_INTERMEDIATE_CFLAGS:+ }-m32 -mstackrealign"
CXXFLAGS="${CLEAR_INTERMEDIATE_CXXFLAGS}${CLEAR_INTERMEDIATE_CXXFLAGS:+ }-m32 -mstackrealign"
LDFLAGS="${CLEAR_INTERMEDIATE_LDFLAGS}${CLEAR_INTERMEDIATE_LDFLAGS:+ }-m32 -mstackrealign"
%configure --disable-static    --libdir=/usr/lib32 --build=i686-generic-linux-gnu --host=i686-generic-linux-gnu --target=i686-clr-linux-gnu
make  %{?_smp_mflags}
popd
unset PKG_CONFIG_PATH
pushd ../buildavx2/
GOAMD64=v3
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -march=x86-64-v3 -Wl,-z,x86-64-v3 "
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS -march=x86-64-v3 "
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS -march=x86-64-v3 "
%configure --disable-static
make  %{?_smp_mflags}
popd
%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make %{?_smp_mflags} check
cd ../build32;
make %{?_smp_mflags} check || :
cd ../buildavx2;
make %{?_smp_mflags} check || :

%install
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
CLEAR_INTERMEDIATE_CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FCFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CLEAR_INTERMEDIATE_CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS -O3 -Os -fdata-sections -fdebug-types-section -femit-struct-debug-baseonly -ffat-lto-objects -ffunction-sections -flto=auto -fno-semantic-interposition -g1 -gno-column-info -gno-variable-location-views -gz=zstd "
CFLAGS="$CLEAR_INTERMEDIATE_CFLAGS"
CXXFLAGS="$CLEAR_INTERMEDIATE_CXXFLAGS"
FFLAGS="$CLEAR_INTERMEDIATE_FFLAGS"
FCFLAGS="$CLEAR_INTERMEDIATE_FCFLAGS"
ASFLAGS="$CLEAR_INTERMEDIATE_ASFLAGS"
LDFLAGS="$CLEAR_INTERMEDIATE_LDFLAGS"
export SOURCE_DATE_EPOCH=1709573865
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/libXcursor
cp %{_builddir}/libXcursor-%{version}/COPYING %{buildroot}/usr/share/package-licenses/libXcursor/dc664605fdc1798afd260114aa223682b7d810cd || :
export GOAMD64=v2
pushd ../build32/
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
if [ -d %{buildroot}/usr/share/pkgconfig ]
then
pushd %{buildroot}/usr/share/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
GOAMD64=v3
pushd ../buildavx2/
%make_install_v3
popd
GOAMD64=v2
%make_install
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files dev
%defattr(-,root,root,-)
/usr/include/X11/Xcursor/Xcursor.h
/usr/lib64/libXcursor.so
/usr/lib64/pkgconfig/xcursor.pc
/usr/share/man/man3/Xcursor.3
/usr/share/man/man3/XcursorAnimateCreate.3
/usr/share/man/man3/XcursorAnimateDestroy.3
/usr/share/man/man3/XcursorAnimateNext.3
/usr/share/man/man3/XcursorCommentCreate.3
/usr/share/man/man3/XcursorCommentDestroy.3
/usr/share/man/man3/XcursorCommentsCreate.3
/usr/share/man/man3/XcursorCommentsDestroy.3
/usr/share/man/man3/XcursorCursorsCreate.3
/usr/share/man/man3/XcursorCursorsDestroy.3
/usr/share/man/man3/XcursorFileLoad.3
/usr/share/man/man3/XcursorFileLoadAllImages.3
/usr/share/man/man3/XcursorFileLoadImage.3
/usr/share/man/man3/XcursorFileLoadImages.3
/usr/share/man/man3/XcursorFileSave.3
/usr/share/man/man3/XcursorFileSaveImages.3
/usr/share/man/man3/XcursorFilenameLoad.3
/usr/share/man/man3/XcursorFilenameLoadAllImages.3
/usr/share/man/man3/XcursorFilenameLoadCursor.3
/usr/share/man/man3/XcursorFilenameLoadCursors.3
/usr/share/man/man3/XcursorFilenameLoadImage.3
/usr/share/man/man3/XcursorFilenameLoadImages.3
/usr/share/man/man3/XcursorFilenameSave.3
/usr/share/man/man3/XcursorFilenameSaveImages.3
/usr/share/man/man3/XcursorGetDefaultSize.3
/usr/share/man/man3/XcursorGetTheme.3
/usr/share/man/man3/XcursorGetThemeCore.3
/usr/share/man/man3/XcursorImageCreate.3
/usr/share/man/man3/XcursorImageDestroy.3
/usr/share/man/man3/XcursorImageHash.3
/usr/share/man/man3/XcursorImageLoadCursor.3
/usr/share/man/man3/XcursorImagesCreate.3
/usr/share/man/man3/XcursorImagesDestroy.3
/usr/share/man/man3/XcursorImagesLoadCursor.3
/usr/share/man/man3/XcursorImagesLoadCursors.3
/usr/share/man/man3/XcursorImagesSetName.3
/usr/share/man/man3/XcursorLibraryLoadCursor.3
/usr/share/man/man3/XcursorLibraryLoadCursors.3
/usr/share/man/man3/XcursorLibraryLoadImage.3
/usr/share/man/man3/XcursorLibraryLoadImages.3
/usr/share/man/man3/XcursorLibraryPath.3
/usr/share/man/man3/XcursorLibraryShape.3
/usr/share/man/man3/XcursorNoticeCreateBitmap.3
/usr/share/man/man3/XcursorNoticePutBitmap.3
/usr/share/man/man3/XcursorSetDefaultSize.3
/usr/share/man/man3/XcursorSetTheme.3
/usr/share/man/man3/XcursorSetThemeCore.3
/usr/share/man/man3/XcursorShapeLoadCursor.3
/usr/share/man/man3/XcursorShapeLoadCursors.3
/usr/share/man/man3/XcursorShapeLoadImage.3
/usr/share/man/man3/XcursorShapeLoadImages.3
/usr/share/man/man3/XcursorSupportsARGB.3
/usr/share/man/man3/XcursorSupportsAnim.3
/usr/share/man/man3/XcursorTryShapeBitmapCursor.3
/usr/share/man/man3/XcursorTryShapeCursor.3
/usr/share/man/man3/XcursorXcFileLoad.3
/usr/share/man/man3/XcursorXcFileLoadAllImages.3
/usr/share/man/man3/XcursorXcFileLoadImage.3
/usr/share/man/man3/XcursorXcFileLoadImages.3
/usr/share/man/man3/XcursorXcFileSave.3

%files dev32
%defattr(-,root,root,-)
/usr/lib32/libXcursor.so
/usr/lib32/pkgconfig/32xcursor.pc
/usr/lib32/pkgconfig/xcursor.pc

%files lib
%defattr(-,root,root,-)
/V3/usr/lib64/libXcursor.so.1.0.2
/usr/lib64/libXcursor.so.1
/usr/lib64/libXcursor.so.1.0.2

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libXcursor.so.1
/usr/lib32/libXcursor.so.1.0.2

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/libXcursor/dc664605fdc1798afd260114aa223682b7d810cd
